title: "Christoph â€“ Homepage"
description: "Christoph's personal Homepage"
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      toc: true
      toc_sticky: true
      sidebar:
        nav: "main"
        position: left


plugins:
  - jekyll-include-cache


# the following files are not available via the website
exclude:
  - README.md
  - LICENSE
  - scripts/
  - .vscode/
  - Gemfile
  - Gemfile.lock


# site properties
email: chr.mi@web.de
